[data]
auth = [
  { email = "xxx@gmail.com", password = "xxx" }
]

[proxies]
data=[
    "http://username:pass@ip:port",
	"http://username:pass@ip:port",
	"http://username:pass@ip:port",
	"http://username:pass@ip:port",
]